image:
  registry: ghcr.io
  repository: sample-app
  tag: latest
  port: 80
ingress:
  enabled: true
  ingressClassName: public
  entries:
    - name: public
      hosts:
        - hostname: sample-app.apps.demo.tryglueops.onglueops.com
