image:
  registry: docker.io
  repository: nginx
  tag: latest
  port: 80
ingress:
  enabled: true
  ingressClassName: public
  entries:
    - name: public
      hosts:
        - hostname: example-app.apps.demo.tryglueops.onglueops.com
